%% Copyright (C) 2017 Achim D. Brucker, https://www.brucker.ch
%%
%% License:
%%   This program can be redistributed and/or modified under the terms
%%   of the LaTeX Project Public License Distributed from CTAN
%%   archives in directory macros/latex/base/lppl.txt; either
%%   version 1 of the License, or any later version.
%%   OR
%%   The 2-clause BSD-style license.
%%
\NeedsTeXFormat{LaTeX2e}[1994/06/01]
\ProvidesClass{lh-businesscard}%
  [2017/04/14 v0.0  LaTeX class implementing the cooperate design of LogicalHacking.com]

\LoadClass[inverse]{lh-presentation}


\usepackage{qrcode}
\usepackage{pst-barcode}
\geometry{top=0mm,bottom=0mm,left=0mm,right=0mm,paperwidth=90mm,paperheight=60mm}
\endinput
